#!/bin/bash

# makepkg - Part of spkg(Sourim Package manager)
# Copyright (C) 2024 r2u2team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

MAKEPKG_VERSION="1.0"

LOG_PREFIX=">"

COLOR_RESET="\e[0m"
COLOR_BOLD="\e[1m"
COLOR_RED="\e[31m"
COLOR_GREEN="\e[32m"
COLOR_BLUE="\e[34m"
COLOR_CYAN="\e[36m"
COLOR_YELLOW="\e[1;33m"

FLAG_INSTALL=
FLAG_QUIET=
FLAG_ARCH=`uname -m`
FLAG_INPUT=pkgbuild
ROOT=$PWD

# Script:

show_msg() {
    echo -e "$COLOR_BOLD$1 $COLOR_RESET$COLOR_BOLD${@:2}$COLOR_RESET"
}
show_log() {
    show_msg "${COLOR_BLUE}$LOG_PREFIX" $@
}
show_err() {
    show_msg "${COLOR_RED}$LOG_PREFIX" $@
    exit 1
}
download() {
    show_log "Downloading $(basename $1)"
    wget --show-progress $1 || exit 1
}
fetch_source() {
    [[ ${#1} != 64 ]] && show_err "Invalid hash for the source code is specified"
    [[ -z $2 ]]       && show_err "Specifies an empty link for the source code"

    if [[ ! -f $(basename $2) ]]; then
        download $2
        fetch_source $@
        return
    fi

    show_log "\tChecking the hash(sha256)"
    echo "$1 $(basename $2)" | sha256sum -c --status \
                            || show_err "The file does not match the hash"
}

while getopts "hviqo:" opt; do
    case $opt in
        i)  FLAG_INSTALL=y        ;;
        q)  FLAG_QUIET=y          ;;
        o)  FLAG_OUTPUT="$OPTARG" ;;
        a)  FLAG_ARCH="$OPTARG"   ;;
        v)
            echo "makepkg v$MAKEPKG_VERSION"
            exit 1
        ;;
        ? | h)
            echo "Usage: $0 OPTIONS FILE"
            echo "Options:"
            echo "  -h         Show this message"
            echo "  -v         Show version"
            echo "  -i         Install package after build"
            echo "  -a ARCH    Architecture package(defaults to your system)"
            echo "  -q         Disable build log"
            exit 1
        ;;
    esac
done
shift $((OPTIND -1))

if [[ $EUID == 0 ]]; then
    echo -ne $COLOR_RED$COLOR_BOLD
    echo "Makepkg was run as root user, are you sure you want to continue?"
    read -p "Press Enter to continue."
    echo -ne $COLOR_RESET
fi
if [[ ! -f $1 ]]; then
    show_err "'$1' file not found"
fi


show_log "Reading $1"
source $1 || exit 1

# Creating cache/temp dirs
rm -rf /tmp/spkg
mkdir -p /tmp/spkg
for d in src root; do
    if [[ ! -d ~/.cache/spkg-makepkg/$name/$d ]]; then
        show_log "Creating cache dir"
        rm -rf ~/.cache/spkg-makepkg/$name/root
        mkdir -p ~/.cache/spkg-makepkg/$name/{src,root} || exit 1
    fi
done

#####################################################

command pushd ~/.cache/spkg-makepkg/$name > /dev/null

cd src

# Fetching source
show_log "Checking/Download source"
for ((i = 0; i < ${#source[@]}; i++)); do
    src="${source[$i]}"
    hash="${source_sha256[$i]}"
    
    fetch_source $hash $src
done

# Unpacking source
show_log "Unpacking sources:"
for src in ${source[@]}; do
    srcfile=$(basename $src)

    show_log "\tUnpacking '$srcfile'..."

    if [[ $srcfile == *".tar"* ]]; then
        tar xf $srcfile || exit 1
    elif [[ $srcfile == *".zip" ]]; then
        unzip -q $srcfile || exit 1
    else
        show_err "Unsupported archive file '$srcfile'"
    fi
done

# Building
show_log "Start building package..."
BUILD_TMP=$(declare -f package)
FAKEROOT_COMMAND="name=\"$name\"; version=\"$version\"; depends=\"$depends\"; $BUILD_TMP; package ~/.cache/spkg-makepkg/$name/root"
if [[ -z $FLAG_QUIET ]]; then
    fakeroot -- bash -c "$FAKEROOT_COMMAND" || exit 1
else
    fakeroot -- bash -c "$FAKEROOT_COMMAND > /dev/null" || exit 1
fi

# Packing rootfs
show_log "Packing rootfs..."
cd ../root
XZ_OPT="-e9 -T`nproc`" tar cfJ /tmp/spkg/rootfs.tar.xz * || exit 1

# Packing package
cd /tmp/spkg

echo "name=\"$name\"" > /tmp/spkg/meta || exit 1
echo "ver=\"$version\"" >> /tmp/spkg/meta || exit 1
echo "depends=\"$depends\"" >> /tmp/spkg/meta || exit 1

show_log "Packing..."
tar cf $ROOT/$name-$version-$FLAG_ARCH.spkg * || exit 1

rm -rf /tmp/spkg || exit 1


command popd > /dev/null

show_log "Done!"